Simples Pimples Kit
===================

Inspired by the wonderful [Simples Pimples](http://opengameart.org/content/simple-broad-purpose-tileset) spritesheet, I decided to create a public domain jumpstart for building HTML5 games using this spritesheet and the [Phaser](http://phaser.io) library.

To make the spritesheet easier to work with, I took the liberty of splitting it up into categories. Those categories:

* !(Bombs)[images/bombs.png]
* !(Bottles)[images/bottles.png]
* !(Boulders)[images/boulders.png]
* !(Bricks)[images/bricks.png]
* !(Cans)[images/cans.pngs]
* !(Cartons)[images/cartons.png]
* !(Caves)[images/caves.png]
* !(Characters)[images/characters.png]
* !(Cheese)[images/cheese.png]
* !(Chests)[images/chests.png]
* !(Columns)[images/columns.png]
* !(Control Panels)[images/control-panels.png]
* !(Doors)[images/doors.png]
* !(Drinks)[images/drinks.png]
* !(Drops)[images/drops.png]
* !(Drugs)[images/drugs.png]
* !(Foliage)[images/foliage.png]
* !(Fruits & Vegetables)[images/fruits-n-vegetables.png]
* !(Ladders)[images/ladders.png]
* !(Lakes)[images/lakes.png]
* !(Lock & Keys)[images/lock-n-keys.png]
* !(Meat)[images/meat.png]
* !(Meds)[images/meds.png]
* !(Metal Blocks)[images/metal-blocks.png]
* !(Pavers)[images/pavers.png]
* !(Pinball)[images/pinball.png]
* !(Sandwiches)[images/sandwiches.png]
* !(Sign Posts)[images/sign-posts.png]
* !(Skulls)[images/skulls.png]
* !(Stones)[images/stones.png]
* !(Sweets)[images/sweets.png]
* !(Torches)[images/torches.png]
* !(Treasure)[images/treasure.png]
* !(Warning Blocks)[images/warning-blocks.png]
